title: GDG Rio de Janeiro
description:  GDG (Google Developer Group) Rio é um grupo de desenvolvedores entusiastas dos produtos Google. Nós amamos o que fazemos e estamos sempre querendo aprender mais. Mantenha-se conectado para participar dos eventos e fazer parte do grupo!
show_downloads: false
theme: jekyll-theme-slate
